modLoader="javafml"
loaderVersion="[2,)"
license="Not specified"

[[mods]]
modId="war_for_eternity"
version="1.0.0"
displayName="War For Eternity"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Lenovo, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.war_for_eternity]]
    modId="neoforge"
    type="required"
    versionRange="[20.4.223,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.war_for_eternity]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.4]"
    ordering="NONE"
    side="BOTH"


[[dependencies.war_for_eternity]]
    modId="geckolib"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.war_for_eternity]]
    modId="playeranimator"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

